### ISSUE TITLE
FuXi=1.4 failur at importing FunctionalProperty in testOWL

### ISSUE THREAD

**Issue by sheon** [RDFLib/FuXi#11]
I just installed FuXi from https://github.com/RDFLib/FuXi... then I tried the testOWL from FuXi webpage and I got the following errors:

<    from rdflib.Namespace import Namespace
ImportError: No module named Namespace >

which I then checked the module should be rdflib.namespace (with lower case), and this was resolved but the next error is

< from rdflib.OWL import FunctionalityProperty
ImportError: No module named OWL>

I couldn't fix this one :)... but the question is that what is wrong? is it because of the rdflib version as mentioned here :
http://answers.semanticweb.com/questions/1805/rdflib-troubles 
the current rdflib version is 4.2.0 so I assume these problems should be resolved.

is there any version of FuXi which does not have such problems. I checked the run_tests included in the FuXi_master it also return no module named Literal, or Graph.

**Comment by gromgull** [comment]
>  testOWL from FuXi webpage  

This is an alternative version of fuxi for newer version of rdflib. Using things from the "main" versino of Fuxi will break.

**Comment by sheon** [comment]
Thanks I used the testOWL.py from the same source (GitHub) and the error is "no module named Collection".

**Comment by gromgull** [comment]
I am sorry, but this FuXi (I dont know about the other one), as you can see the last activity was over 2 years ago, maybe we changed something in rdflib since then.

**Comment by sheon** [comment]
Do we have a newer version? I could not install the FuXi using the FuXi installation (https://code.google.com/p/fuxi/wiki/Installation_Testing) on my Windows 7 system. So I found this one here and I easily installed. I really need a working version of FuXi for my reaserch but so far I have no success. Could you help me with that?
